version: '2'
services:
  db:
    env_file: .env
    image: mysql:5.7
    volumes:
      - "./.data/db:/var/lib/mysql"
      - "./.data/share:/share"
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"

  wordpress:
    env_file: .env
    depends_on:
      - db
    build: ./acme
    volumes:
      - "./www:/var/www/html"
    links:
      - db
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
